language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION compile test package
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e9a7bafc07a46c80ded6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
sudo: false
